# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mnist-nbdev',
                'doc_host': 'https://mlu-wx.github.io',
                'git_url': 'https://github.com/mlu-wx/mnist-nbdev',
                'lib_path': 'mnist_nbdev'},
  'syms': {'mnist_nbdev.core': {'mnist_nbdev.core.foo': ('core.html#foo', 'mnist_nbdev/core.py')}}}
